name: flutter_bakong_khqr_example
description: "Demonstrates how to use the flutter_bakong_khqr plugin."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  flutter_bakong_khqr:
    path: ../

  cupertino_icons: ^1.0.8

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:

  uses-material-design: true

  
