name: flutter_bakong_khqr
description: "This plugin use for generate Bakong KHQR for online payment in Cambodia"
version: 0.0.1+2
homepage:
repository: https://github.com/sokhatim/flutter_bakong_khqr
issue_tracker: https://github.com/sokhatim/flutter_bakong_khqr/issues

environment:
  sdk: ^3.5.3
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  qr_flutter: ^4.1.0
  flutter_svg: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  
  plugin:
    platforms:
      android:
        package: com.example.flutter_bakong_khqr
        pluginClass: FlutterBakongKhqrPlugin

  # To add assets to your plugin package, add an assets section, like this:
  assets:
    - assets/khqr/
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
