name: flutter_bakong_khqr
description: "This plugin use for generate Bakong KHQR for online payment in Cambodia"
version: 0.0.2
homepage:
repository: https://github.com/sokhatim/flutter_bakong_khqr
issue_tracker: https://github.com/sokhatim/flutter_bakong_khqr/issues

screenshots:
  - description: "Flutter Bakong KHQR"
    path: assets/flutter_bakong_khqr_logo.jpg

topics:
  - bakong
  - khqr
  - bakong-khqr
  - bakong-khqr-code

environment:
  sdk: ^3.5.3
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  qr_flutter: ^4.1.0
  flutter_svg: ^2.0.11
  money2: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  
  plugin:
    platforms:
      android:
        package: com.example.flutter_bakong_khqr
        pluginClass: BakongKhqrPlugin

  assets:
    - assets/khqr/
  
  fonts:
    - family: NunitoSans
      fonts:
        - asset: assets/fonts/NunitoSans_7pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/NunitoSans_7pt-Bold.ttf
          weight: 700
